### ISSUE TITLE
Class not found exception for RmObjectJsonDeSerializer

### ISSUE THREAD

**Issue by Xelpha** [ehrbase/ehrbase_client_library#28]
Calling the createObjectMapper function in "DefaultRestClient" class triggers a class not found exception for RmObjectJsonDeSerializer. This is dependent on the ehrbase jar. It would be good for the sub dependencies to be loaded with it's dependencies.

**Comment by stefanspiska** [comment]
This sound like a duplicate of https://github.com/ehrbase/ehrbase_client_library/issues/21
for me
