### ISSUE TITLE
Missing NodeId Elements

### ISSUE THREAD

**Issue by alannicol** [ehrbase/ehrbase_client_library#9]
Hi

I have been using the OptSkeletonbuilder class to generate a composition ("composition = (Composition) cut.generate(template);") based upon a couple of templates that I have been working with. However in order for the compositions to be generated without error, I have had to manually add <node_id/> elements to each element with a tag of "Children" e.g. <children xsi:type="C_COMPLEX_OBJECT">, as the template I am using only has nodeId fields where there is a set value. I am just wondering if this a known issue with the client library, and that nodeId's should not necessarily be an expected field of the Children tag (as per the openEhr standard) or perhaps there is an issue with the templates I am using and the nodeId field should always be present?

Any help you can provide would be most appreciated. 

Thanks
Alan

**Comment by stefanspiska** [comment]
Hi,

can you please provide an example of a Template which generates errors.

**Comment by alannicol** [comment]
Hi 

This is the template we are using that has caused the errors.

Thanks
Alan

[NHS_Care_Scotland_NDS-Patients-own-testing-devices.v0.opt.zip](https://github.com/ehrbase/ehrbase_client_library/files/4186578/NHS_Care_Scotland_NDS-Patients-own-testing-devices.v0.opt.zip)

**Comment by Geisterfalle** [comment]
@alannicol Can you confirm that the template should look like this? 
![image](https://user-images.githubusercontent.com/2463423/74351677-bdfc3d80-4db7-11ea-8e29-bc97c77ea141.png)

The item part in the protocol section looks a bit strange to me. Would be good if you can clarify.

**Comment by stefanspiska** [comment]
@alannicol 
Can you take look at https://github.com/ehrbase/ehrbase_client_library/tree/feature/%239_fix_npe_messing_node_id

with that I could generate a Entity from your template.

**Comment by alannicol** [comment]
@stefanspiska 

Yes, that now works thanks. Not sure what you have changed but I can now use the openEhr templates generated by the Marand Archetype Designer tool with the client-library, and it generates the compositions as expected.

Thanks for all your help.

**Comment by alannicol** [comment]
@Geisterfalle 

I am not sure to be honest, as it was not me who created the templates it was a clinician who is working on a project that I am involved with.
